# Plugins
plugins: #Deprecation of gems:
- jekyll-sitemap
safe: false #https://stackoverflow.com/a/19086256

# Build Settings
markdown: kramdown
permalink: pretty
#exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /automation/
  - README.md
  - LICENSE.txt
  - CNAME


# Site Settings
title: "Cloud Alpes 2023"
email: "cloudalpes@gmail.com"
description: "Cloud Alpes, c'est l'événement qui se tient à Lyon et dédié à la Tech avec pour thématique le Cloud, l’Architecture et tout ce qui se rapporte aux pratiques de développement : Finops, Greenops, Serverless, Cloud Native, technique de déploiement, sécurisation…"
baseurl: "/"
url: "https://info.cloudalpes.fr"
canvaurl: "https://cloudalpes.fr"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Cloud Alpes"
organizerAlternateName: "Cloud Alpes - DevOps Group"
organizerDescription: "Cloud Alpes est une initiative lancée par quelques Lyonnais passionnés de Tech et désireux de mettre en avant ce qu'il se fait dans la région et partager expériences et nouveautés technologiques"
organizerEmail: "cloudalpes@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://cloudalpes.fr"

# Head
metaKeywords: "insa, conf, event, cloud, cloudalpes, devops, programming, code, programmation, developers, développeurs, lyon"
author: "David Aparicio, Association Cloud Alpes"
twitterAccount: "@CloudAlpes"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.jpg"
socialImageSrcFacebook: "/img/seo/sharing-facebook.jpg"

# Documents
c4pUrl: "https://s.42l.fr/cloudalpes2023cfp"
c4sponsorsUrl: "/assets/Kit_Sponsoring_Cloud_Alpes_2023.pdf"


# Navigation
navigationLinks:
#  - {permalink: "/", text: "Accueil"}
 - {link: "https://www.cloudalpes.fr/", text: "Accueil"}
#  - {permalink: "/#sponsors", text: "Partenaires"}
#  - {link: "https://s.42l.fr/cloudalpes2023cfp", text: "CFP"}
#  - {link: "https://s.42l.fr/cloudalpes2023ticket", text: "Billeterie"}
 - {permalink: "/blog/", text: "Blog"}
#  - {permalink: "/team/", text: "Équipe"}
 # - {permalink: "/schedule/", text: "Programme"}
 #- {permalink: "/speakers/", text: "Orateurs"}
 - {permalink: "/logistics/", text: "Accès"}
# - {permalink: "/hackathon/", text: "Hackathon"}

bottomNavigationLinks:
 - {link: "https://s.42l.fr/cloudalpes2023cfp", text: "Devenir orateur"}
rightNavigationButtons:
 - {link: "https://s.42l.fr/cloudalpes2023ticket", text: "Acheter un billet"}
#  - {link: "https://s.42l.fr/cloudalpes2023cfp", text: "Proposer un talk"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Cloud Alpes 2023 : <typeout>"
eventDate: "6 Septembre 2023"
typeoutTextValues: '"", "DevOps ", "Architecture", "Méthodologie", "Hors-piste"'
typeoutFallback: "1ère édition"
heroButtons:
 - {link: "https://s.42l.fr/cloudalpes2023sponsor", text: "Devenir sponsor"}
 - {link: "/#tickets", text: "Acheter un billet"}

# About Block
aboutTitle: "Cloud Alpes"
aboutObjectif: "Notre objectif: promouvoir le partage de connaissance au sein de la communauté tech de Lyon."
aboutActions: "Nos actions pour l'atteindre: organisation d'une confèrence annuelle et financement d'event meetup tech."
aboutBlock:
 - {title: "Conférence", image: "conference.jpg", text: "Un évènement dédié aux communautés Cloud/DevOps, avec des orateurs de renommée" }
 - {title: "Ateliers", image: "workshop.jpg", text: "Une journée entière d'ateliers sur divers sujets. Venez apprivoiser votre technologie préférée !" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1", specialCharacter: "", info: "ère édition", detail: "Notre ADN: Partage & Convivialité"}
 - {count: "200", specialCharacter: "+", info: "participants attendus", detail: "de toute la France"}
 - {count: "8", specialCharacter: "+", info: "heures", detail: "de Tech et pas que !"}
 - {count: "10", specialCharacter: "+", info: "orateurs", detail: "de France et d'ailleurs"}
# - {count: "1", specialCharacter: "", info: "piste", detail: "pour plus de découvertes"}

# Latest News Block
latestNewsTitle: "Dernières nouvelles"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Quelques speakers"
rockstarSpeakersButtonText: "Voir tous les speakers"

# Location Block
locationBlockTitle: "Venue"
eventLocationName: "Amphi Gaston Berger - INSA de Lyon"
eventLocationLink: "https://www.insa-lyon.fr/fr/"
eventStreetAddress: "503 Rue de la Physique"
eventAddressLocality: "Villeurbanne"
eventAddressLocalityRegion: "Rhône"
eventPostalCode: "69100"
eventAddressCountry: "France"
eventStartTime: "2023-09-26T08:00"
eventDoorTime: "08:00"
eventEndTime: "2023-09-06T20:00"
eventPlaceCoordinates: "45.78247747584086, 4.872048429445763"
mapCenterCoordinates: "45.7824569,4.8720491"
mapMobileCenterCoordinates: "45.7824569,4.8720491"

# Venue Block
venueBlockTitle: "Lieu"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Amphi Gaston Berger (INSA)"
venueFeatures: ["350 places", "Accessible, PMR et en transport en commun", "Facile d'accès depuis le centre-ville de Lyon"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Partagez sur les réseaux avec "
twitterHashTag: "cloudalpes"
twitterFeed: "" #"http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organisateurs"
partnersTitle: "Partenaires"
partnersC4sponsorsButton: "Devenir un partenaire"

# Sponsors Block
sponsorsTitle: "Sponsors"
sponsorsC4sponsorsButton: "Devenir un sponsor"

# Subscribe Block
subscribeImage: "lyon.jpg"
subscribeTitle: "S'inscrire à la newsletter"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Les inscriptions seront ouvertes très bientôt. Le nombre de billets est limité. Restez à l'écoute !"

# Tickets Block
ticketsTitle: "Billeterie"
ticketsInfo: "Les billets donnent accès à toutes les sections de la conférence, aux pauses-café, et au déjeuner. L'hébergement n'est pas inclus dans le prix du billet."
ticketsOffers:
 -
  name: "Early Bird"
  price: "20"
  priceCurrency: "EUR"
  ticketsNumber: "80"
  ribbon: "-50%"
  buyButtonLink: "https://s.42l.fr/cloudalpes2023ticket"
  buyButtonText: "Acheter"
  ticketContentList: ["Mystère complet sur le programme", "Déjeuner inclus"]
  validFrom: "2023-05-01T10:00"
  validThrough: "2023-07-01T23:59"
 -
  name: "Standard"
  price: "40"
  priceCurrency: "EUR"
  ticketsNumber: "220"
  ribbon: ""
  featured: true
  buyButtonLink: "https://s.42l.fr/cloudalpes2023ticket"
  buyButtonText: "Acheter"
  ticketContentList: ["Programme connu", "Déjeuner inclus"]
  validFrom: "2023-07-01T00:00"
  validThrough: "2023-09-04T23:59"
  disabled: true
 -
  name: "Étudiant"
  price: "20"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  buyButtonLink: "https://s.42l.fr/cloudalpes2023ticket"
  buyButtonText: "Acheter"
  additionalInfo: "Une carte d'étudiant en cours de validité doit être présentée à l'enregistrement de la conférence. Sans carte d'étudiant à l'enregistrement, le billet sera annulé sans remboursement."
  ticketContentList: ["Tarif spécial avec déjeuner", "Nécessite une carte étudiante valide"]
  validFrom: "2023-05-01T10:00"
  validThrough: "2023-09-04T23:59"
  soldOut: false
  soldOutText: "Indisponible"

# Footer
socialLinks:
 - {link: "https://twitter.com/Cloud_Alpes", icon: "twitter"}
 - {link: "https://www.linkedin.com/company/cloud-alpes/", icon: "linkedin"}
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
# - {link: "https://twitter.com/intent/user?screen_name=Cloud_Alpes", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Liens"
  links:
   - {link: "https://www.insa-lyon.fr/fr/", text: "INSA de Lyon"}
   - {link: "https://if.insa-lyon.fr/", text: "Département Informatique"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:cloudalpes@gmail.com", text: "cloudalpes@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code de conduite"}

# Blog
blogTitle: "Dernières nouvelles"
blogCommentsEnabled: false
discusShortName: "cloudalpes"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "A propos"
aboutUs: "Cloud Alpes est une initiative lancée par quelques Lyonnais passionnés de Tech et désireux de mettre en avant ce qu'il se fait dans la région et partager expériences et nouveautés technologiques"

# Logistics Find Way Block
findWayTitle: "Trouver un chemin pour y aller"
findWayDistance: "Distance"
findWayDriving: "VOITURE"
findWayWalking: "MARCHANT"
findWayBicycling: "VELO"
findWayTransit: "TRANSPORT"
findWayFindFlight: "Trouver un vol"
logisticsMapCenterCoordinates: "45.7824569,4.8720491"
logisticsMapMobileCenterCoordinates: "45.7824569,4.8720491"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "lyon.jpg" #direction-details.jpg"
directionDetailsTitle: "Se rendre à Lyon"
directionDetailsCards:
 - {title: "Depuis l'aéroport", information: "L'aéroport est situé à la frontière de la ville. Il est facilement accessible en voiture, en transports publics ou en taxi. Plus d'informations sont disponibles à l'adresse suivante <a href='https://www.lyonaeroports.com/'>site web de l'Aéroport Saint-Exupéry</a>."}
 - {title: "En transports publics", information: "<a href='https://citymapper.com/lyon'>Citymapper</a> est disponible à Lyon. Vous pouvez donc trouver votre chemin dans <a href='https://citymapper.com/lyon'>Citymapper</a> ou sur le site des <a href='https://www.tcl.fr/itineraires'>TCL</a>. De plus, vous pouvez télécharger n'importe quelle application de transport public hors ligne disponible pour Lyon."}
 - {title: "Hôtels", information: "Lyon dispose de nombreux hôtels et auberges de jeunesse de qualité. De plus amples informations seront disponibles ultérieurement."}
directionDetailsWideCards:
 # -
 #  title: "Des questions?"
 #  subCards:
 #   -
 #    title: "Hôtels"
 #    links:
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
 #   -
 #    title: "Enregistrement"
 #    links:
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
 #   -
 #    title: "Détails pour les participants"
 #    links:
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
 #     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
 #
# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
#aboutHackathonTitle: "Meet our themes"
#hackathonRows:
# - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
# - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
# - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
#judgesImage: "judges.jpg"
#judgesTitle: "Judges"

# Hackathon Prizes Block
#prizesTitle: "Prizes"
#prizes:
# - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
# - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
# - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
#hackathonLocationBlockTitle: "Location"
#hackathonLocationName: "Communa"
#hackathonLocationLink: "http://communa.net.ua/"
#hackathonStreetAddress: "1 Halytska St"
#hackathonAddressLocality: "Lviv"
#hackathonAddressLocalityRegion: "Lvivska"
#hackathonPostalCode: "79000"
#hackathonAddressCountry: "Ukraine"
#hackathonTimeTitle: "Hack through"
#hackathonStartTime: "2014-10-24T10:00"
#hackathonDoorTime: "09:00"
#hackathonEndTime: "2014-10-25T00:00"
#viewOnMap: "View on Google Maps"
#hackathonPlaceCoordinates: "49.840999, 24.031144"
#hackathonMapCenterCoordinates: "49.840696, 24.028754"
#hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
