# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build Jekyll site to push to GitHub Pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
  schedule:
    #https://crontab.guru/#37_13_*_*_3
    - cron: "37 13 * * 3"

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source
  contents: write    # fatal: unable to access 'repo_url': The requested URL returned error: 403

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  buildAndUpload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - name: Get cached gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
        # Specify the Jekyll source location as a parameter
        #jekyll_src: 'sample_site'

    # Deploy to the github-pages environment, via bot (pages-build-deployment)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

#https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site  
#https://jekyllrb.com/docs/continuous-integration/github-actions/
#https://github.com/MichaelCurrin/jekyll-actions-quickstart
#https://github.com/Arishti-Live/arishti-live.github.io/blob/master/.github/workflows/jekyll.yml